export const ayVerificationArticleStyle = `<style>
.ayv-editorial{margin-top:52px}
.ayv-editorial-cover{position:relative;display:grid;grid-template-columns:minmax(0,1.3fr) minmax(220px,.7fr);align-items:center;gap:32px;min-height:320px;padding:clamp(28px,5vw,56px);overflow:hidden;border-radius:25px;background:radial-gradient(circle at 86% 14%,#267fbd88 0,transparent 34%),linear-gradient(125deg,#102c49,#0c4169 64%,#075a89);color:#fff;box-shadow:0 20px 42px #102c4926}
.ayv-editorial-cover:before{position:absolute;inset:0;background-image:linear-gradient(#ffffff0b 1px,transparent 1px),linear-gradient(90deg,#ffffff0b 1px,transparent 1px);background-size:28px 28px;mask-image:linear-gradient(90deg,transparent,#000);content:"";pointer-events:none}
.ayv-editorial-cover-copy{position:relative;z-index:1}.ayv-editorial-cover .ayv-editorial-kicker{display:inline-flex;align-items:center;gap:9px;padding:7px 12px;border:1px solid #8dd6ff78;border-radius:999px;background:#c9eaff16;color:#cdefff;font-size:10px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}
.ayv-editorial-cover h2{max-width:620px;margin:22px 0 14px;color:#fff;font-size:clamp(34px,4.8vw,56px);font-weight:800;line-height:1.1;letter-spacing:-.045em}.ayv-editorial-cover p{max-width:550px;margin:0;color:#d4e9f5;font-size:15px;line-height:1.8}
.ayv-editorial-cover-tags{display:flex;flex-wrap:wrap;gap:8px;margin-top:26px}.ayv-editorial-cover-tags span{padding:6px 10px;border:1px solid #b8e4ff5c;border-radius:999px;color:#d8efff;font-size:10px;font-weight:750}
.ayv-editorial-art{position:relative;z-index:1;display:grid;place-items:center;min-height:225px}.ayv-editorial-paper{position:relative;width:168px;height:204px;padding:26px 21px;border:1px solid #e0f3ff;border-radius:15px;background:#f8fcff;box-shadow:0 24px 48px #03192d6b;transform:rotate(6deg)}
.ayv-editorial-paper:before{display:block;width:90px;height:10px;margin:0 0 23px;border-radius:5px;background:#1a6a9e;content:""}.ayv-editorial-paper:after{position:absolute;right:19px;bottom:21px;width:45px;height:45px;border:8px solid #d6edfa;border-radius:10px;background:repeating-conic-gradient(#146390 0 25%,#fff 0 50%) 0/13px 13px;content:""}
.ayv-editorial-line{display:block;width:100%;height:6px;margin-bottom:12px;border-radius:4px;background:#d5e5ef}.ayv-editorial-line:nth-child(2){width:72%}.ayv-editorial-line:nth-child(3){width:85%}
.ayv-editorial-check{position:absolute;right:0;top:26px;display:grid;place-items:center;width:78px;height:78px;border:6px solid #d9f5fb;border-radius:25px;background:#0b9aab;color:#fff;font-size:36px;font-weight:800;box-shadow:0 14px 28px #001b3160;transform:rotate(-9deg)}
.ayv-editorial-body{max-width:900px;margin:0 auto;padding:clamp(27px,4vw,49px) 4px 0;color:#3b5268;font-size:15px;line-height:1.9}.ayv-editorial-body>p:first-child{font-size:17px;color:#28435b}.ayv-editorial-body h3{margin:37px 0 10px;color:#102c49;font-size:clamp(22px,2.5vw,28px);line-height:1.25}.ayv-editorial-body p{margin:0 0 15px}.ayv-editorial-body a{font-weight:700}.ayv-editorial-body ul,.ayv-editorial-body ol{margin:12px 0 22px;padding-left:25px}.ayv-editorial-body li{padding-left:5px;margin-bottom:8px}
.ayv-editorial-callout{margin:28px 0;padding:20px 23px;border-left:4px solid #0878d2;border-radius:0 13px 13px 0;background:#eef8ff}.ayv-editorial-callout p{margin:0}.ayv-editorial-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:20px 0 25px}.ayv-editorial-step{padding:18px;border:1px solid #d9e7f2;border-radius:14px;background:#fff}.ayv-editorial-step strong{display:block;margin-bottom:6px;color:#0878d2;font-size:11px;letter-spacing:.12em}.ayv-editorial-step span{display:block;color:#3b5268;font-size:13px;line-height:1.6}
.ayv-editorial-faq{margin-top:35px;padding-top:15px;border-top:1px solid #d9e7f2}.ayv-editorial-faq details{padding:16px 0;border-bottom:1px solid #d9e7f2}.ayv-editorial-faq summary{color:#102c49;font-weight:750;cursor:pointer}.ayv-editorial-faq details p{margin:10px 0 0}
@media(max-width:700px){.ayv-editorial-cover{grid-template-columns:1fr;gap:10px}.ayv-editorial-art{min-height:160px}.ayv-editorial-paper{transform:scale(.75) rotate(6deg)}.ayv-editorial-check{right:calc(50% - 105px);top:3px;transform:scale(.75) rotate(-9deg)}.ayv-editorial-steps{grid-template-columns:1fr}}
</style>`;

export const ayVerificationArticleHtml = `<article class="ayv-editorial" aria-labelledby="ayv-editorial-title">
  <header class="ayv-editorial-cover"><div class="ayv-editorial-cover-copy"><span class="ayv-editorial-kicker">AY TERCÜME · BELGE GÜVENLİĞİ</span><h2 id="ayv-editorial-title">Resmî Belge Doğrulama</h2><p>Yeminli tercüme ve diğer belge işlemlerinde güven, belgenin kaynağını ve doğru sürümünü kontrol etmekle başlar.</p><div class="ayv-editorial-cover-tags"><span>QR kod ile sorgulama</span><span>Belge numarası ile sorgulama</span><span>Kayıt ve dosya karşılaştırması</span></div></div><div class="ayv-editorial-art" aria-hidden="true"><div class="ayv-editorial-paper"><i class="ayv-editorial-line"></i><i class="ayv-editorial-line"></i><i class="ayv-editorial-line"></i></div><div class="ayv-editorial-check">✓</div></div></header>
  <div class="ayv-editorial-body"><p>Bir tercüme veya tasdik dosyası başka bir kişiye ya da kuruma ulaştığında, elindeki nüshanın hangi kayda ait olduğunu bilmek önemlidir. AY Tercüme belge doğrulama sayfası, tarafımızdan yayımlanan QR kodlu belgelerin kayıt bilgilerini <strong>QR kodu okutarak veya belge numarasını girerek</strong> incelemenizi sağlar. Dosya yayımlanmışsa görüntülenen PDF ile elinizdeki belgeyi de karşılaştırabilirsiniz.</p>
  <h3>Yeminli tercüme doğrulama nasıl yapılır?</h3><p>AY Tercüme tarafından düzenlenen bir <a href="https://aytercume.com/yeminli-tercume/">yeminli tercüme</a> üzerindeki QR kodunu sayfanın üstündeki kamera alanıyla okutun. Kamerayı kullanamıyorsanız belge numarasını sorgulama kutusuna yazın. Açılan kayıttaki belge numarasını, tarihi, belge türünü ve ilgili bilgileri elinizdeki nüshayla karşılaştırın. PDF mevcutsa sayfa düzenini, adları, tarihleri, sayıları ve ekleri de gözden geçirin.</p><p>Kayıt bulunamaması tek başına belgenin sahte olduğunu göstermez. Numaranın doğru girildiğini kontrol edin; belge yeni düzenlendiyse veya dosya henüz yayımlanmadıysa AY Tercüme ofisiyle iletişime geçin.</p>
  <h3>Noter onaylı tercüme, apostil ve diğer belgeler</h3><p>Aynı sorgulama, AY Tercüme’nin QR kodlu kayıt olarak yayımladığı <a href="https://aytercume.com/noter-onayli-tercume/">noter onaylı tercüme</a> dosyaları ve <a href="https://aytercume.com/apostil/">apostil sürecine</a> ilişkin dosyalar için de kullanılabilir. Diploma, transkript, nüfus belgesi, vekâletname, sözleşme ve şirket evrakı gibi farklı belge türlerinde asıl kontrol, sorgulama sonucunun sunulan nüshayla eşleşmesidir.</p><div class="ayv-editorial-callout"><p><strong>Doğrulamanın kapsamı:</strong> Bu sayfa AY Tercüme’nin yayımladığı kaydı gösterir. Noter işleminin, apostilin veya başka bir resmî onayın ilgili kurum nezdindeki geçerliliğini ayrıca teyit etmez. Belgeyi kabul edecek kurumun istediği onay ve kontrol yöntemini ayrıca izleyin.</p></div>
  <h3>Belge doğrulama neden önemlidir?</h3><p>Belge numarası ve QR bağlantısı, alıcı kişinin doğru kayda ulaşmasını kolaylaştırır. Tarih, belge türü ve varsa PDF karşılaştırması; yanlış nüsha, eksik ek veya aktarım sırasında oluşan karışıklıkları fark etmeye yardımcı olur. Özellikle resmî başvuru, eğitim, hukuk ve ticari işlemlerde küçük bir isim, tarih ya da sayfa farkı bile dosyanın yeniden incelenmesini gerektirebilir.</p>
  <h3>AY Tercüme neden ayrıntılara dikkat eder?</h3><p>Resmî belge tercümesinde metnin anlamı kadar adların, numaraların, tarihlerin, kurum adlarının, mühürlerin ve ek sayfaların doğru aktarılması da önemlidir. AY Tercüme, belgenin kullanılacağı kurum ve ülkeye göre yeminli tercüme, noter onayı ve gerekirse apostil adımlarını planlar. Doğrulama kaydı da teslim edilen nüshanın bilgilerini sonradan kontrol etmeye yardımcı olan bu sürecin bir parçasıdır.</p>
  <h3>Belgenizi üç adımda kontrol edin</h3><div class="ayv-editorial-steps"><div class="ayv-editorial-step"><strong>01 · SORGULAYIN</strong><span>Üstteki alandan QR kodu okutun veya belge numarasını girin.</span></div><div class="ayv-editorial-step"><strong>02 · KARŞILAŞTIRIN</strong><span>Kayıt bilgilerini ve varsa PDF’yi elinizdeki nüshayla karşılaştırın.</span></div><div class="ayv-editorial-step"><strong>03 · SORUN</strong><span>Bir bilgi uyuşmuyorsa veya kayıt görünmüyorsa AY Tercüme’ye ulaşın.</span></div></div>
  <div class="ayv-editorial-faq"><h3>Sık sorulan sorular</h3><details><summary>Belge numarasıyla doğrulama yapabilir miyim?</summary><p>Evet. QR kodu okutamıyorsanız bu sayfanın üstündeki belge numarası alanını kullanabilirsiniz.</p></details><details><summary>Doğrulama sonucu noter veya apostil onayını da doğrular mı?</summary><p>Hayır. Sorgulama AY Tercüme’nin yayımladığı kaydı gösterir. Noter ve apostil işlemlerine ilişkin resmî doğrulamayı ilgili kurumun yöntemiyle yapın.</p></details><details><summary>Dosya görüntülenmiyorsa ne yapmalıyım?</summary><p>Belge kaydı görünüp PDF henüz yayımlanmamış olabilir. Daha sonra tekrar bakın veya aşağıdaki iletişim bilgilerinden AY Tercüme’ye ulaşın.</p></details></div></div>
</article>`;
