export const ttaaVerificationArticleHtml = `<article class="ayv-editorial" aria-labelledby="ttaa-editorial-title">
  <header class="ayv-editorial-cover"><div class="ayv-editorial-cover-copy"><span class="ayv-editorial-kicker">TTAA · DOCUMENT ASSURANCE</span><h2 id="ttaa-editorial-title">Official Document Verification</h2><p>Check the source and version of a translation or attestation file before you rely on it.</p><div class="ayv-editorial-cover-tags"><span>Scan a QR code</span><span>Search a document number</span><span>Compare the record and PDF</span></div></div><div class="ayv-editorial-art" aria-hidden="true"><div class="ayv-editorial-paper"><i class="ayv-editorial-line"></i><i class="ayv-editorial-line"></i><i class="ayv-editorial-line"></i></div><div class="ayv-editorial-check">✓</div></div></header>
  <div class="ayv-editorial-body"><p>When an official document or translation reaches a university, employer, business partner or public authority, the recipient needs a reliable way to identify the record it belongs to. This TTAA document verification page lets you <strong>scan a QR code or search by document number</strong> to find a record published by Turkish Translation &amp; Attestation Agency. If a PDF is available, you can compare it with the copy you received.</p>
  <h3>How to verify a certified or sworn translation</h3><p>For a TTAA translation carrying a QR code, use the camera tool above or select an image of the code. You can also enter the document number printed on the file. Compare the returned number, date, document type and other displayed details with your copy. When the PDF is present, review names, dates, page order, figures and attachments as well.</p><p>TTAA provides <a href="https://turkishtranslation.com.tr/translation/">translation services</a> for personal, academic, legal and business documents. The translation format requested by the receiving authority may be certified, sworn or notarized, depending on the case. A match on this page confirms the published TTAA record; the receiving authority decides whether the document meets its submission requirements.</p>
  <h3>Attestation, apostille and other document services</h3><p>The same search method can be used for TTAA files issued with a verification record in connection with <a href="https://turkishtranslation.com.tr/services/attestation/">document attestation</a> or <a href="https://turkishtranslation.com.tr/services/apostille-and-legalization/">apostille and legalization support</a>. It may also help recipients compare records for diplomas, certificates, powers of attorney, contracts and company documents. Availability depends on whether a QR verification record was published for the particular file.</p><div class="ayv-editorial-callout"><p><strong>What this check covers:</strong> This page confirms the details TTAA has published for its own file. It does not independently authenticate a notary act, apostille, embassy legalization or the original document. Use the relevant authority’s own verification method for those formalities.</p></div>
  <h3>Why does document verification matter?</h3><p>A QR link or document number gives the recipient a direct route to the intended record. Comparing the date, document type and available PDF helps reveal a wrong version, missing attachment or transcription error before the file is submitted. Small differences in names, numbers, dates or pages can matter in education, employment, legal and commercial applications.</p>
  <h3>Why TTAA checks the details carefully</h3><p>A sound translation and attestation workflow starts with the document’s purpose, destination and receiving authority. TTAA reviews the details that can change how a file is prepared: names, dates, numbers, institutional terms, stamps, signatures and supporting pages. Translation, notarization, apostille and legalization are distinct stages, arranged when the case requires them. The verification record gives recipients another way to check that they are looking at the intended TTAA file.</p>
  <h3>Verify your document in three steps</h3><div class="ayv-editorial-steps"><div class="ayv-editorial-step"><strong>01 · SEARCH</strong><span>Scan the QR code or enter the document number in the tool above.</span></div><div class="ayv-editorial-step"><strong>02 · COMPARE</strong><span>Match the record details and any available PDF against your copy.</span></div><div class="ayv-editorial-step"><strong>03 · ASK</strong><span>If a detail differs or no record appears, contact TTAA using the details below.</span></div></div>
  <div class="ayv-editorial-faq"><h3>Frequently asked questions</h3><details><summary>Can I verify a document without scanning its QR code?</summary><p>Yes. Enter the document number in the search box above to look for its TTAA verification record.</p></details><details><summary>Does this result verify an apostille or notary approval?</summary><p>No. It displays TTAA’s published file record. Check a notary act, apostille or legalization through the responsible authority when that formal verification is needed.</p></details><details><summary>What if the record or PDF is missing?</summary><p>Check the document number for typing errors. A PDF may be added after the record is created. If you still cannot match the file, contact TTAA before relying on the document.</p></details></div></div>
</article>`;
